apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
