apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ required "auth-service.secret.RABBITMQ_URL is required" .Values.secret.RABBITMQ_URL | quote }}
  MONGO_URI: {{ required "auth-service.secret.MONGO_URI is required" .Values.secret.MONGO_URI | quote }}
  JWT_SECRET: {{ required "auth-service.secret.JWT_SECRET is required" .Values.secret.JWT_SECRET | quote }}
