services:
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - auth-service
      - task-service
      - notification-service
      - analytics-service
      - rabbitmq
    networks:
      - backend

  auth-service:
    build: 
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - mongo-auth
      - rabbitmq
    networks:
      - backend
  
  task-service:
    build: 
      context: .
      dockerfile: ./apps/task-service/Dockerfile
    container_name: task-service
    env_file:
      - ./apps/task-service/.env
    depends_on:
      - mongo-task
      - rabbitmq
      - redis
    networks:
      - backend

  notification-service:
    build: 
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
    container_name: notification-service
    env_file:
      - ./apps/notification-service/.env
    depends_on:
      - mongo-notification
      - rabbitmq
      - redis
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
  
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3001:3000"
    networks:
      - backend
    depends_on:
      - prometheus

  jaeger: 
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Web UI portal
      - "4317:4317"   # OTLP gRPC port (receives traces)
    networks:
      - backend

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
  
    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - backend


  mongo-auth:
    image: mongo:7
    container_name: mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - backend

  mongo-task:
    image: mongo:7
    container_name: mongo-task
    ports:
      - "27018:27017"
    # Start MongoDB in replica set mode to support transactions, listening on all interfaces inside the Docker network
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_task_data:/data/db
    networks:
      - backend
  
  mongo-notification:
    image: mongo:7
    container_name: mongo-notification
    ports:
      - "27019:27017"
    volumes:
      - mongo_notification_data:/data/db
    networks:
      - backend

  mongo-analytics:
    image: mongo:7
    container_name: mongo-analytics
    ports:
      - "27020:27017"
    volumes:
      - mongo_analytics_data:/data/db
    networks:
      - backend

  analytics-service:
    build:
      context: .
      dockerfile: ./apps/analytics-service/Dockerfile
    container_name: analytics-service
    env_file:
      - ./apps/analytics-service/.env
    depends_on:
      - mongo-analytics
      - kafka
      - redis
    networks:
      - backend

volumes:
  mongo_auth_data:
  mongo_task_data:
  mongo_notification_data:
  mongo_analytics_data:
  kafka-data:

networks:
  backend: