services:
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - auth-service
      - task-service
      - notification-service
      - rabbitmq
    networks:
      - backend

  auth-service:
    build: 
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - mongo-auth
      - rabbitmq
    networks:
      - backend
  
  task-service:
    build: 
      context: .
      dockerfile: ./apps/task-service/Dockerfile
    container_name: task-service
    env_file:
      - ./apps/task-service/.env
    depends_on:
      - mongo-task
      - rabbitmq
    networks:
      - backend

  notification-service:
    build: 
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
    container_name: notification-service
    env_file:
      - ./apps/notification-service/.env
    depends_on:
      - mongo-notification
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  mongo-auth:
    image: mongo:7
    container_name: mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - backend

  mongo-task:
    image: mongo:7
    container_name: mongo-task
    ports:
      - "27018:27017"
    volumes:
      - mongo_task_data:/data/db
    networks:
      - backend
  
  mongo-notification:
    image: mongo:7
    container_name: mongo-notification
    ports:
      - "27019:27017"
    volumes:
      - mongo_notification_data:/data/db
    networks:
      - backend

volumes:
  mongo_auth_data:
  mongo_task_data:
  mongo_notification_data:

networks:
  backend: