apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ required "notification-service.secret.RABBITMQ_URL is required" .Values.secret.RABBITMQ_URL | quote }}
  MONGO_URI: {{ required "notification-service.secret.MONGO_URI is required" .Values.secret.MONGO_URI | quote }}
