apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ required "api-gateway.secret.RABBITMQ_URL is required" .Values.secret.RABBITMQ_URL | quote }}
  JWT_SECRET: {{ required "api-gateway.secret.JWT_SECRET is required" .Values.secret.JWT_SECRET | quote }}
