apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-auth-pvc
  namespace: workflowhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: mongo-auth-pv
  resources:
    requests:
      storage: 1Gi
