apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "analytics-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "analytics-service.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ include "analytics-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "analytics-service.fullname" . }}-config
            - secretRef:
                name: {{ include "analytics-service.fullname" . }}-secret
          readinessProbe:
            exec:
              command:
                - node
                - /app/scripts/check-rabbitmq.js
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - readlink /proc/1/exe | grep -q node
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          startupProbe:
            exec:
              command:
                - node
                - /app/scripts/check-rabbitmq.js
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
