apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-task-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/workflowhub/mongo-task
