apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongo-notification.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
