replicaCount: 1

image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3
  startup:
    periodSeconds: 5
    failureThreshold: 12
